name: Publish 🚀

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAMEE: ane-frontend-data
  AZURE_WEBAPP_PACKAGE_PATH: './publish'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Restore
        run: dotnet restore ./ane-frontend-data.sln

      - name: Build
        run: dotnet build ./ane-frontend-data.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./ane-frontend-data.sln --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ./ane-frontend-data/data/**
          if-no-files-found: error

      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: ~/wwwroot/data

      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAMEE }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
